/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardStorageRouteImport } from './routes/dashboard.storage'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardServersRouteImport } from './routes/dashboard.servers'
import { Route as DashboardSecurityRouteImport } from './routes/dashboard.security'
import { Route as DashboardNetworkingRouteImport } from './routes/dashboard.networking'
import { Route as DashboardLogsRouteImport } from './routes/dashboard.logs'
import { Route as DashboardKubernetesRouteImport } from './routes/dashboard.kubernetes'
import { Route as DashboardInfrastructureRouteImport } from './routes/dashboard.infrastructure'
import { Route as DashboardHermesRouteImport } from './routes/dashboard.hermes'
import { Route as DashboardDockerRouteImport } from './routes/dashboard.docker'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardAlertsRouteImport } from './routes/dashboard.alerts'
import { Route as DashboardAiAssistantRouteImport } from './routes/dashboard.ai-assistant'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStorageRoute = DashboardStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServersRoute = DashboardServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSecurityRoute = DashboardSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNetworkingRoute = DashboardNetworkingRouteImport.update({
  id: '/networking',
  path: '/networking',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogsRoute = DashboardLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKubernetesRoute = DashboardKubernetesRouteImport.update({
  id: '/kubernetes',
  path: '/kubernetes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInfrastructureRoute = DashboardInfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHermesRoute = DashboardHermesRouteImport.update({
  id: '/hermes',
  path: '/hermes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDockerRoute = DashboardDockerRouteImport.update({
  id: '/docker',
  path: '/docker',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAlertsRoute = DashboardAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiAssistantRoute = DashboardAiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard/ai-assistant': typeof DashboardAiAssistantRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/docker': typeof DashboardDockerRoute
  '/dashboard/hermes': typeof DashboardHermesRoute
  '/dashboard/infrastructure': typeof DashboardInfrastructureRoute
  '/dashboard/kubernetes': typeof DashboardKubernetesRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/networking': typeof DashboardNetworkingRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/servers': typeof DashboardServersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/storage': typeof DashboardStorageRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard/ai-assistant': typeof DashboardAiAssistantRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/docker': typeof DashboardDockerRoute
  '/dashboard/hermes': typeof DashboardHermesRoute
  '/dashboard/infrastructure': typeof DashboardInfrastructureRoute
  '/dashboard/kubernetes': typeof DashboardKubernetesRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/networking': typeof DashboardNetworkingRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/servers': typeof DashboardServersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/storage': typeof DashboardStorageRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard/ai-assistant': typeof DashboardAiAssistantRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/docker': typeof DashboardDockerRoute
  '/dashboard/hermes': typeof DashboardHermesRoute
  '/dashboard/infrastructure': typeof DashboardInfrastructureRoute
  '/dashboard/kubernetes': typeof DashboardKubernetesRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/networking': typeof DashboardNetworkingRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/servers': typeof DashboardServersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/storage': typeof DashboardStorageRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/dashboard/ai-assistant'
    | '/dashboard/alerts'
    | '/dashboard/analytics'
    | '/dashboard/docker'
    | '/dashboard/hermes'
    | '/dashboard/infrastructure'
    | '/dashboard/kubernetes'
    | '/dashboard/logs'
    | '/dashboard/networking'
    | '/dashboard/security'
    | '/dashboard/servers'
    | '/dashboard/settings'
    | '/dashboard/storage'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/dashboard/ai-assistant'
    | '/dashboard/alerts'
    | '/dashboard/analytics'
    | '/dashboard/docker'
    | '/dashboard/hermes'
    | '/dashboard/infrastructure'
    | '/dashboard/kubernetes'
    | '/dashboard/logs'
    | '/dashboard/networking'
    | '/dashboard/security'
    | '/dashboard/servers'
    | '/dashboard/settings'
    | '/dashboard/storage'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/dashboard/ai-assistant'
    | '/dashboard/alerts'
    | '/dashboard/analytics'
    | '/dashboard/docker'
    | '/dashboard/hermes'
    | '/dashboard/infrastructure'
    | '/dashboard/kubernetes'
    | '/dashboard/logs'
    | '/dashboard/networking'
    | '/dashboard/security'
    | '/dashboard/servers'
    | '/dashboard/settings'
    | '/dashboard/storage'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/storage': {
      id: '/dashboard/storage'
      path: '/storage'
      fullPath: '/dashboard/storage'
      preLoaderRoute: typeof DashboardStorageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/servers': {
      id: '/dashboard/servers'
      path: '/servers'
      fullPath: '/dashboard/servers'
      preLoaderRoute: typeof DashboardServersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/security': {
      id: '/dashboard/security'
      path: '/security'
      fullPath: '/dashboard/security'
      preLoaderRoute: typeof DashboardSecurityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/networking': {
      id: '/dashboard/networking'
      path: '/networking'
      fullPath: '/dashboard/networking'
      preLoaderRoute: typeof DashboardNetworkingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/logs': {
      id: '/dashboard/logs'
      path: '/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof DashboardLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/kubernetes': {
      id: '/dashboard/kubernetes'
      path: '/kubernetes'
      fullPath: '/dashboard/kubernetes'
      preLoaderRoute: typeof DashboardKubernetesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/infrastructure': {
      id: '/dashboard/infrastructure'
      path: '/infrastructure'
      fullPath: '/dashboard/infrastructure'
      preLoaderRoute: typeof DashboardInfrastructureRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/hermes': {
      id: '/dashboard/hermes'
      path: '/hermes'
      fullPath: '/dashboard/hermes'
      preLoaderRoute: typeof DashboardHermesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/docker': {
      id: '/dashboard/docker'
      path: '/docker'
      fullPath: '/dashboard/docker'
      preLoaderRoute: typeof DashboardDockerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/alerts': {
      id: '/dashboard/alerts'
      path: '/alerts'
      fullPath: '/dashboard/alerts'
      preLoaderRoute: typeof DashboardAlertsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai-assistant': {
      id: '/dashboard/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/dashboard/ai-assistant'
      preLoaderRoute: typeof DashboardAiAssistantRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAiAssistantRoute: typeof DashboardAiAssistantRoute
  DashboardAlertsRoute: typeof DashboardAlertsRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardDockerRoute: typeof DashboardDockerRoute
  DashboardHermesRoute: typeof DashboardHermesRoute
  DashboardInfrastructureRoute: typeof DashboardInfrastructureRoute
  DashboardKubernetesRoute: typeof DashboardKubernetesRoute
  DashboardLogsRoute: typeof DashboardLogsRoute
  DashboardNetworkingRoute: typeof DashboardNetworkingRoute
  DashboardSecurityRoute: typeof DashboardSecurityRoute
  DashboardServersRoute: typeof DashboardServersRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStorageRoute: typeof DashboardStorageRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAiAssistantRoute: DashboardAiAssistantRoute,
  DashboardAlertsRoute: DashboardAlertsRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardDockerRoute: DashboardDockerRoute,
  DashboardHermesRoute: DashboardHermesRoute,
  DashboardInfrastructureRoute: DashboardInfrastructureRoute,
  DashboardKubernetesRoute: DashboardKubernetesRoute,
  DashboardLogsRoute: DashboardLogsRoute,
  DashboardNetworkingRoute: DashboardNetworkingRoute,
  DashboardSecurityRoute: DashboardSecurityRoute,
  DashboardServersRoute: DashboardServersRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStorageRoute: DashboardStorageRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
